#!/bin/bash

echo "| image=iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAAS9QTFRF/////f7/5vb83vT73/T79fv+VcXrILPlI7TlH7Pl8/v+ObvnAKbgAKfhA6jhL7jmCaviOLvnObvoBqriAajhAqjhAKjhBariDazirOP1LLfmN7vnIrPlg9TwHLLkjdjyb87uqeH1HrLksOT2LbfmNrvnLrjmseT2d9DvJLTlYsnsltvzG7HkDKziA6nhDazjNrrn9Pv+OrzoKbbmtOX2EK3jEq7jteX2J7XmO7zo/P7/VMTruOb3L7fmAKfgN7rntub2D63jWMXrkdnyftLwot/0IbPlreP1mdzz4fX7MLjmD6zih9bxu+j3q+L1vOj3edHvCariPLzo6Pf8vun3QL3oP73oHLHkAafhNbrny+352vL7ftPwPr3oJrXlJ7XlQr7piNbx4vX8/v//5fb8l2aeIgAAAAFiS0dEAIgFHUgAAAAJcEhZcwAAAEgAAABIAEbJaz4AAADASURBVBjTY2BgZGJmgQJmJkYGBgZWNnYOCGDnZGMFCnBx8/CCAR+/gCAXSECIV1hEVExcQEJSShosIC0jKycvpaCopKwCEVBVU5fT0NTS1kES0OUVE9WTUEcSEAMCfZiAAUJAFSRgaGRsYgoSMDO3sAS5w8razMbWTkyMx97B0ckKKMDgzOvi6iYubOyuIOIB4jN4enn7+Cr6+QcEBgWDBRhCjEXdQsPCIyKjGKAgOiY2Lj4hMYkBDpK5UlIMIUwAm+ActhsQ8s4AAAAldEVYdGRhdGU6Y3JlYXRlADIwMTYtMDctMjVUMjA6NTU6MjcrMDA6MDAdQVmNAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDE2LTA3LTI1VDIwOjU1OjI3KzAwOjAwbBzhMQAAAEZ0RVh0c29mdHdhcmUASW1hZ2VNYWdpY2sgNi43LjgtOSAyMDE0LTA1LTEyIFExNiBodHRwOi8vd3d3LmltYWdlbWFnaWNrLm9yZ9yG7QAAAAAYdEVYdFRodW1iOjpEb2N1bWVudDo6UGFnZXMAMaf/uy8AAAAYdEVYdFRodW1iOjpJbWFnZTo6aGVpZ2h0ADE5Mg8AcoUAAAAXdEVYdFRodW1iOjpJbWFnZTo6V2lkdGgAMTky06whCAAAABl0RVh0VGh1bWI6Ok1pbWV0eXBlAGltYWdlL3BuZz+yVk4AAAAXdEVYdFRodW1iOjpNVGltZQAxNDY5NDgwMTI3eX+PcAAAAA90RVh0VGh1bWI6OlNpemUAMEJClKI+7AAAAFZ0RVh0VGh1bWI6OlVSSQBmaWxlOi8vL21udGxvZy9mYXZpY29ucy8yMDE2LTA3LTI1LzAzNGZjMmU5ZDUwYjBiZDcwNmJiMGYxYWY3NDg2NDNhLmljby5wbmcPcqBoAAAAAElFTkSuQmCC"
echo ---

#https://www.gocomics.com/pearlsbeforeswine/2002/1/7

RANDOM_DATE=$RANDOM%5000	# about numebr of days since epoch
RANDOM_DATE=$(( RANDOM_DATE * 86400 ))
FIRST_COMIC_DATE=1010361600	#1989-04-16

NOW_COMIC_DATE=$(( FIRST_COMIC_DATE + RANDOM_DATE ))

NOW_COMIC_DATE_STRING=$(date -r $NOW_COMIC_DATE +'%Y/%m/%d')

PBS_COMIC_URL="https://www.gocomics.com/pearlsbeforeswine/$NOW_COMIC_DATE_STRING"

DATA_STRING=$(curl --silent $PBS_COMIC_URL | grep 'item-comic-image')

DATA_IMAGE_VALUE=$(echo $DATA_STRING | sed 's/"//g;s/.* data-srcset=\([^\s]*\)/\1/' | awk '{print $1}')

IMAGE=$(base64 <(curl --silent "$DATA_IMAGE_VALUE"))

echo "| image=$IMAGE"
echo ---
echo "$PBS_COMIC_URL | size=14 href='$PBS_COMIC_URL'"

echo ---
echo "Refresh... | refresh=true"
